### ISSUE TITLE
Dockerfile improved

### ISSUE THREAD

**Issue by ixpict** [jay7x/etc-hosts-proxy#14]
Hello! I see that you've significantly revised the Dockerfile and everything has improved, but I have a couple of comments:

1. Hiding the Dockerfile in .dockerfile may not be the best idea. Historically, in most repositories, it's stored in the root directory so that one can easily navigate to the repository, execute the 'docker build' command, and compile the project. Could you consider adhering to this convention?

2. I notice that you haven't set default environment variables, instead moving them to the README. While this is a viable approach, many clients and other "life simplifying" tools use this information for easy importing (e.g. Synology's Dockerfile interface, IDEs, and so on).

Please think about these points as they could make the project easier to use for others.

Your hard work is appreciated!

**Comment by jay7x** [comment]
Hi!

1. If the `.dockerfile` contents is good enough for general use I can move it to `Dockerfile`, np. I was not really sure if it suits all the cases as it's just a wrapped binary w/o any OS.
2. Do you mean that some tools are exposing the Dockerfile's `ENV` block? If so I'm totally fine to add them. I wasn't aware of such behavior 🤔

**Comment by ixpict** [comment]
This isn't strictly necessary, it's just that sometimes it can be more convenient :)
